CREDENTIALS_ACTIONS = {
      # ============================================================
    # 500-599 CREDENTIAL ATTACKS / AUTH CHECKS
    # ============================================================
    500: {
        "name": "BRUTEFORCE_SSH",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "hydra",
        "command_template": "hydra -L {userlist_path} -P {passwordlist_path} ssh://{target_ip}",
        "placeholders": ["target_ip", "userlist_path", "passwordlist_path"],
        "parser_family": "hydra",
        "expected_events": ["VALID_CREDENTIAL_FOUND", "LOGIN_FAILED"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_service": ["ssh"],
            "requires_authorization": True,
        },
        "risk_level": "high",
        "description": "Run SSH credential testing in an authorized lab.",
    },

    501: {
        "name": "BRUTEFORCE_FTP",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "hydra",
        "command_template": "hydra -L {userlist_path} -P {passwordlist_path} ftp://{target_ip}",
        "placeholders": ["target_ip", "userlist_path", "passwordlist_path"],
        "parser_family": "hydra",
        "expected_events": ["VALID_CREDENTIAL_FOUND", "LOGIN_FAILED"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_service": ["ftp"],
            "requires_authorization": True,
        },
        "risk_level": "high",
        "description": "Run FTP credential testing in an authorized lab.",
    },

    502: {
        "name": "BRUTEFORCE_HTTP_LOGIN",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "hydra",
        "command_template": "hydra -L {userlist_path} -P {passwordlist_path} {target_ip} http-post-form \"{login_path}:{login_user_field}=^USER^&{login_pass_field}=^PASS^:{login_failure_string}\"",
        "placeholders": [
            "target_ip",
            "userlist_path",
            "passwordlist_path",
            "login_path",
            "login_user_field",
            "login_pass_field",
            "login_failure_string",
        ],
        "parser_family": "hydra_http",
        "expected_events": ["VALID_CREDENTIAL_FOUND", "LOGIN_FAILED"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_http_login_form": True,
            "requires_authorization": True,
        },
        "risk_level": "high",
        "description": "Run HTTP form credential testing when login form parameters are known.",
    },

    510: {
        "name": "CHECK_FTP_ANONYMOUS_LOGIN",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "nmap",
        "command_template": "nmap --script ftp-anon -p {target_port} {target_ip}",
        "placeholders": ["target_ip", "target_port"],
        "parser_family": "nmap_ftp_anon",
        "expected_events": ["FTP_ANON_LOGIN_ALLOWED"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_target_port": True,
            "requires_service": ["ftp"],
        },
        "risk_level": "low",
        "description": "Check whether anonymous FTP login is allowed.",
    },

    520: {
        "name": "CHECK_SSH_KNOWN_CREDS",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "sshpass",
        "command_template": "sshpass -p {password} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o MACs=+hmac-md5,hmac-sha1,hmac-sha1-96,hmac-md5-96 {username}@{target_ip} 'whoami && id && hostname && uname -a'",
        "placeholders": ["target_ip", "username", "password"],
        "parser_family": "ssh_login",
        "default_port": 22,
        "default_username": "msfadmin",
        "default_password": "msfadmin",
        "service_names": ["ssh"],
        "expected_events": [
            "VALID_CREDENTIAL_FOUND",
            "SESSION_OPENED",
            "SESSION_USER_DETECTED",
            "SESSION_PRIVILEGES_DETECTED",
            "SESSION_HOSTNAME_DETECTED",
            "SESSION_SYSTEM_DETECTED",
            "SESSION_CLOSED",
        ],
        "preconditions": {
            "requires_target_ip": True,
            "requires_service": ["ssh"],
            "requires_credentials": True,
            "requires_authorization": True,
        },
        "risk_level": "high",
        "description": "Validate known SSH credentials and execute basic session validation commands.",
    },

    521: {
        "name": "CHECK_TELNET_KNOWN_CREDS",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "expect",
        "command_template": "timeout 25 expect -c 'spawn telnet {target_ip} {target_port}; expect \"login:\"; send \"{username}\\r\"; expect \"Password:\"; send \"{password}\\r\"; expect \"$\"; send \"whoami && id && hostname && uname -a\\r\"; expect \"$\"; send \"exit\\r\"; expect eof'",
        "placeholders": ["target_ip", "target_port", "username", "password"],
        "parser_family": "telnet_login",
        "default_port": 23,
        "default_username": "msfadmin",
        "default_password": "msfadmin",
        "service_names": ["telnet"],
        "expected_events": [
            "VALID_CREDENTIAL_FOUND",
            "SESSION_OPENED",
            "SESSION_USER_DETECTED",
            "SESSION_PRIVILEGES_DETECTED",
            "SESSION_HOSTNAME_DETECTED",
            "SESSION_SYSTEM_DETECTED",
            "SESSION_CLOSED",
        ],
        "preconditions": {
            "requires_target_ip": True,
            "requires_target_port": True,
            "requires_service": ["telnet"],
            "requires_credentials": True,
            "requires_authorization": True,
        },
        "risk_level": "high",
        "description": "Validate known Telnet credentials using expect and execute basic session validation commands.",
    },


    522: {
        "name": "CHECK_MYSQL_KNOWN_CREDS",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "mysql",
        "command_template": "mysql -h {target_ip} -P {target_port} -u {username} -p{password} -e 'SELECT VERSION();'",
        "placeholders": ["target_ip", "target_port", "username", "password"],
        "parser_family": "mysql_client",
        "expected_events": ["VALID_CREDENTIAL_FOUND", "DB_LOGIN_SUCCESS"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_target_port": True,
            "requires_service": ["mysql"],
            "requires_credentials": True,
            "requires_authorization": True,
        },
        "risk_level": "medium",
        "description": "Validate known MySQL credentials.",
    },

    523: {
        "name": "CHECK_POSTGRES_KNOWN_CREDS",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "psql",
        "command_template": "PGPASSWORD={password} psql -h {target_ip} -p {target_port} -U {username} -c 'SELECT version();'",
        "placeholders": ["target_ip", "target_port", "username", "password"],
        "parser_family": "postgres_client",
        "expected_events": ["VALID_CREDENTIAL_FOUND", "DB_LOGIN_SUCCESS"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_target_port": True,
            "requires_service": ["postgresql"],
            "requires_credentials": True,
            "requires_authorization": True,
        },
        "risk_level": "medium",
        "description": "Validate known PostgreSQL credentials.",
    },

    524: {
        "name": "CHECK_TOMCAT_MANAGER_CREDS",
        "category": "credential_attack",
        "phase": "credential_attack",
        "tool": "curl",
        "command_template": "curl -s -u {username}:{password} --max-time 10 http://{target_ip}:{target_port}/manager/html",
        "placeholders": ["target_ip", "target_port", "username", "password"],
        "parser_family": "tomcat_manager",
        "expected_events": ["VALID_CREDENTIAL_FOUND", "TOMCAT_MANAGER_ACCESS_GRANTED"],
        "preconditions": {
            "requires_target_ip": True,
            "requires_target_port": True,
            "requires_service": ["http", "tomcat"],
            "requires_credentials": True,
            "requires_authorization": True,
        },
        "risk_level": "medium",
        "description": "Validate Tomcat Manager credentials.",
    },
}