    # ============================================================
    # 100-199 LOCAL ATTACKER CONTEXT
    # ============================================================
LOCAL_CONTEXT_ACTIONS = {
    100: {
        "name": "INSPECT_LOCAL_HOSTNAME",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "hostname",
        "command_template": "hostname",
        "placeholders": [],
        "parser_family": "generic_text",
        "expected_events": ["LOCAL_HOSTNAME_DETECTED"],
        "preconditions": {},
        "risk_level": "safe",
        "description": "Inspect local attacker hostname.",
    },
    101: {
        "name": "INSPECT_IP_A",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "ip",
        "command_template": "ip a",
        "placeholders": [],
        "parser_family": "linux_ip_addr",
        "expected_events": ["NET_INFO"],
        "description": "Inspect local Linux network interfaces.",
    },
    # 101: ("INSPECT_IP_A", "ip a"),
    102: {
        "name": "INSPECT_IP_R",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "ip",
        "command_template": "ip r",
        "placeholders": [],
        "parser_family": "linux_ip_route",
        "expected_events": ["ROUTE_TABLE"],
        "description": "Inspect local Linux routing table.",
    },
    # 102: ("INSPECT_IP_R", "ip r"),
    103: {
        "name": "INSPECT_IP_NEIGH",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "ip",
        "command_template": "ip neigh",
        "placeholders": [],
        "parser_family": "linux_ip_neigh",
        "expected_events": ["ARP_TABLE"],
        "description": "Inspect local Linux ARP table.",
    },
    104: {
        "name": "INSPECT_SS_LISTENERS",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "ss",
        "command_template": "ss -tulpn",
        "placeholders": [],
        "parser_family": "linux_ss",
        "expected_events": ["PORT_LISTENER_DETECTED"],
        "preconditions": {},
        "risk_level": "safe",
        "description": "Inspect local listening TCP/UDP sockets.",
    },
    105: {
        "name": "PING_FOCUS_HOST",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "ping",
        "command_template": "ping -c 1 -W 2 {target_ip}",
        "placeholders": ["target_ip"],
        "parser_family": "generic_ping",
        "expected_events": ["PING_RESPONSE"],
        "preconditions": {
            "requires_target_ip": True,
        },
        "risk_level": "safe",
        "description": "Ping the focused host once.",
    },

    106: {
        "name": "TRACE_ROUTE_TO_HOST",
        "category": "local_inspection",
        "phase": "attacker_context",
        "tool": "traceroute",
        "command_template": "traceroute {target_ip}",
        "placeholders": ["target_ip"],
        "parser_family": "traceroute",
        "expected_events": ["ROUTE_HOP_DETECTED"],
        "preconditions": {
            "requires_target_ip": True,
        },
        "risk_level": "safe",
        "description": "Trace network path to the focused host.",
    },
}